# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



# seedの見直しintroduced_dateとか（モデルと合わせる）、日付処理とベンチ、


# Admin.create(name: "parcom", password: "aaaaaa")

# User.create(name: "内灘町", email: "uchinada@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", zip: "920-0265", prefecture: "石川県", city: "河北郡内灘町", street: "字大学１丁目２番地１", address: "石川県河北郡内灘町字大学１丁目２番地１", tel: "111-1111", municipality: "内灘町", division: "〇〇課", image: nil, profile: "内灘町の〇〇課です。", notification: "", flag: "", admin_memo: "")
# User.create(name: "富山市", email: "toyama@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", zip: "930-8510", prefecture: "富山県", city: "富山市", street: "新桜町７−３８", address: "富山県富山市新桜町７−３８", tel: "111-1111", municipality: "富山市", division: "〇〇課", image: nil, profile: "富山市の〇〇課です。", notification: "OK", flag: "", admin_memo: "")
# User.create(name: "かほく市", email: "kahoku@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", zip: "929-1195", prefecture: "石川県", city: "かほく市", street: "宇野気ニ８１", address: "石川県かほく市宇野気ニ８１", tel: "111-1111", municipality: "かほく市", division: "〇〇課", image: nil, profile: "かほく市の〇〇課です。", notification: "", flag: "", admin_memo: "")
# User.create(name: "金沢市", email: "kanazawa@example.com", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", zip: "920-0962", prefecture: "石川県", city: "金沢市", street: "広坂１丁目１−１", address: "石川県金沢市広坂１丁目１−１", tel: "111-1111", municipality: "金沢市", division: "〇〇課", image: nil, profile: "金沢市の〇〇課です。", notification: "", flag: "", admin_memo: "")

# Park.create(user_id: 1, name: "内灘サンセットパーク", zip: "920-0265", prefecture: "石川県", city: "河北郡内灘町", street: "大学１丁目４−１", address: "石川県河北郡内灘町大学１丁目４−１", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/YXRTdPgcPPBQ5XtT6", website: "https://u-sp.jp/", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')
# Park.create(user_id: 1, name: "内灘町総合公園", zip: "920-0264", prefecture: "石川県", city: "河北郡内灘町", street: "宮坂に", address: "石川県河北郡内灘町字大学１丁目２番地１", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/4YUvMsbHqPdPphXP6", website: "https://www.hot-ishikawa.jp/spot/4714", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')
# Park.create(user_id: 1, name: "ハマナス恐竜公園", zip: "920-0268", prefecture: "石川県", city: "河北郡内灘町", street: "ハマナス２丁目１８５", address: "石川県河北郡内灘町ハマナス２丁目１８５", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/gHQevHqjSwv7gTqo6", website: "https://uchinadakankou.com/spot/dinosaurpark", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')
# Park.create(user_id: 1, name: "白帆台第４公園", zip: "920-0269", prefecture: "石川県", city: "河北郡内灘町", street: "白帆台２丁目５９０", address: "石川県河北郡内灘町白帆台２丁目５９０", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/YuTNGGgiUy6YtmnE6", website: "https://www.kanazawalabo.net/shop/shop.shtml?s=2079", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')
# Park.create(user_id: 2, name: "富岩運河環水公園", zip: "930-0805", prefecture: "富山県", city: "富山市", street: "湊入船町１", address: "富山県富山市湊入船町１", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/cEGQPRPdLHVEqz6G7", website: "http://www.kansui-park.jp/", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')
# Park.create(user_id: 2, name: "富山城址公園", zip: "930-0081", prefecture: "富山県", city: "富山市", street: "本丸１", address: "富山県富山市本丸１", hours: '{"Mon":"00:00-00:00","Tue":"00:00-00:00","Wed":"00:00-00:00","Thu":"00:00-00:00","Fri":"00:00-00:00","Sat":"00:00-00:00","Sun":"00:00-00:00"}', tel: "111-1111", fee: '{"大人":"100円","子供":"無料"}', map: "https://goo.gl/maps/ncJGBCcp5UQ4DgTQ6", website: "https://joshipark.com/", size: "100平方メートル", profile: "楽しい公園です。", status: "OK", parking_info: '{"無料駐車場":true,"有料駐車場":true, "大型バス駐車OK":true, "駐輪場":true, "EV充電スタンド":true, "立体駐車場":true, "近隣コインパーキング":true}', toilet_info: '{"男女別トイレ":true, "子ども用トイレ":true, "おむつ交換台":true, "ベビーケアルーム":true, "ベビーチェア":true, "オストメイト用設備":true, "バリアフリー":true, "着替え台":true}', playground_info: '{"滑り台":true, "ブランコ":true, "うんてい":true, "ジャングルジム":true, "鉄棒":true, "スプリング遊具":true, "砂場":true, "シーソー":true, "アスレチック":true}', facility_info: '{"美術館　博物館　図書館":true, "体育館・ジム":true, "屋外プール":true, "ドッグ":true}', sports_info: '{"ボール使用OK":true, "スケートボードOK":true, "自転車走行OK":true}', view_info: '{"花見":true, "紅葉":true}', disaster_info: '{"防災指定場所":true}', other_info:'{"無料Wi-Fi提供":true, "ベンチ":true, "ゴミ箱":true, "手洗い場":true, "AED":true, "噴水":true, "芝生":true, "充電スポット":true}')

# Bench.create(park_id: 1, name: "B4ENZ7-1", mac_address: "e45f01422d6b", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Bench.create(park_id: 2, name: "B4ENZ7-2", mac_address: "e45f01422d6c", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Bench.create(park_id: 3, name: "B4ENZ7-3", mac_address: "e45f01422d6d", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Bench.create(park_id: 4, name: "B4ENZ7-4", mac_address: "e45f01422d6e", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Bench.create(park_id: 5, name: "B4ENZ7-5", mac_address: "e45f01422d6f", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Bench.create(park_id: 6, name: "B4ENZ7-6", mac_address: "e45f01422d6g", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)

# Camera.create(park_id: 1, name: "CAMERA-1", mac_address: "e45f01422d6b", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Camera.create(park_id: 2, name: "CAMERA-2", mac_address: "e45f01422d6c", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Camera.create(park_id: 3, name: "CAMERA-3", mac_address: "e45f01422d6d", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Camera.create(park_id: 4, name: "CAMERA-4", mac_address: "e45f01422d6e", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Camera.create(park_id: 5, name: "CAMERA-5", mac_address: "e45f01422d6f", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)
# Camera.create(park_id: 6, name: "CAMERA-6", mac_address: "e45f01422d6g", os_name: "0.1.1", introduced_date: "2022.08.09", position: "36.578,136.648", timer: false)

# Shortcut.create(bench_id: 1, name: "ショートカット１", program: "a,b,c,d")

# Event.create(park_id: 1, name: "イベント１", contents: "イベントがあります。", image: '')
# Event.create(park_id: 1, name: "イベント２", contents: "イベントがあります。", image: '')

# Product.create(park_id: 1, name: "プロダクト１", contents: "こんなプロダクトがあります。")

# Picture.create(park_id: 1, name: "春の景色", picture: )


# TmpDatum.create(data: '{"ID"=>"parcom","MAC_ADDRESS"=>"e45f01422d6b","BATTERY"=>"BATTERY,5.635,MAC,e45f01422d6b","TEMPERATURE"=>"TEMPERATURE,19.75,MAC,e45f01422d6b","FAN"=>"FAN,OFF,MAC,e45f01422d6b","DISPLAY"=>"DISPLAY,OFF,MAC,e45f01422d6b","POSITION"=>"POSITION,LAT:36.383,LON:136.381,MAC,e45f01422d6b","LED"=>"LED,OFF,MAC,e45f01422d6b","COLOR"=>"COLOR,R:0,G:0,B:0,MAC,e45f01422d6b","HUMAN"=>"HUMAN,R:0,L:1,MAC,e45f01422d6b","AUDIO"=>"AUDIO,OFF,MAC,e45f01422d6b","USB5V"=>"USB5V,ON,MAC,e45f01422d6b","WIFIUSE"=>"WIFIUSE,1,MAC,e45f01422d6b","MESSAGE"=>"MESSAGE,none,MAC,e45f01422d6b","MP3"=>"MP3,OFF,MAC,e45f01422d6b","MP4"=>"MP4,OFF,MAC,e45f01422d6b","REQUEST"=>"OK","TIMER"=>"OFF"}', mac_address:"e45f01422d6b")
# TmpMessage.create(message: "FAN,OFF,MAC,e45f01422d6b")

